#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
BuP Paper 14 — beta regression v1

Goal
----
Test whether the fitted spectral exponent beta can be predicted from
the full modular/SFF feature set:

    beta = F(C, gap_ratio, t_dip, t_ramp, slope_ramp, delta3, topology, parameters)

Input
-----
One or more CSV files generated by:
    bup_paper14_sff_features_v3.py

Main tests
----------
1. Standard random K-fold CV.
2. Leave-one-topology-out CV.
3. Leave-one-regime-out CV, where regime = (eta_zz, hx, hz_random).
4. Optional train/test split: train on one CSV, test on another.

Models
------
- LinearRegression
- Ridge
- Lasso
- RandomForestRegressor
- GradientBoostingRegressor

Recommended N=9 regression
--------------------------
python3 papers/paper14_modular_spectral_action/scripts/bup_paper14_beta_regression_v1.py \
    --input-csv papers/paper14_modular_spectral_action/results/sff_features_v3_N9_fixed/paper14_v3_sff_features.csv \
    --candidate induced \
    --min-r2-fit 0.90 \
    --output-dir papers/paper14_modular_spectral_action/results/beta_regression_v1_N9_induced

Recommended Schur regression
----------------------------
python3 papers/paper14_modular_spectral_action/scripts/bup_paper14_beta_regression_v1.py \
    --input-csv papers/paper14_modular_spectral_action/results/sff_features_v3_N9_fixed/paper14_v3_sff_features.csv \
    --candidate schur \
    --min-r2-fit 0.90 \
    --output-dir papers/paper14_modular_spectral_action/results/beta_regression_v1_N9_schur

Train N=9 -> test N=16, if both v3 CSVs exist
---------------------------------------------
python3 papers/paper14_modular_spectral_action/scripts/bup_paper14_beta_regression_v1.py \
    --input-csv papers/paper14_modular_spectral_action/results/sff_features_v3_N9_fixed/paper14_v3_sff_features.csv \
    --test-csv papers/paper14_modular_spectral_action/results/sff_features_v3_N16_optimal/paper14_v3_sff_features.csv \
    --candidate induced \
    --min-r2-fit 0.90 \
    --output-dir papers/paper14_modular_spectral_action/results/beta_regression_v1_trainN9_testN16_induced
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
from sklearn.model_selection import KFold, LeaveOneGroupOut, cross_val_predict
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.inspection import permutation_importance


def parse_args():
    p = argparse.ArgumentParser(description="BuP Paper 14 beta regression v1")
    p.add_argument("--input-csv", nargs="+", required=True,
                   help="One or more paper14_v3_sff_features.csv files.")
    p.add_argument("--test-csv", default=None,
                   help="Optional external test CSV, e.g. N16 after training on N9.")
    p.add_argument("--candidate", default="induced",
                   help="candidate_L to keep: induced, schur, mi_normalized, input_induced, or all.")
    p.add_argument("--family", default="pos",
                   help="Fit family to keep. Default: pos.")
    p.add_argument("--min-r2-fit", type=float, default=0.90,
                   help="Minimum spectral fit R2 for beta rows.")
    p.add_argument("--rmt-min", type=float, default=None,
                   help="Optional minimum K_gap_ratio.")
    p.add_argument("--rmt-max", type=float, default=None,
                   help="Optional maximum K_gap_ratio.")
    p.add_argument("--output-dir", required=True)
    p.add_argument("--random-state", type=int, default=42)
    return p.parse_args()


def read_csvs(paths):
    frames = []
    for p in paths:
        path = Path(p)
        df = pd.read_csv(path)
        df["source_csv"] = str(path)
        df["source_run"] = path.parent.name
        frames.append(df)
    return pd.concat(frames, ignore_index=True)


def filter_df(df, args):
    d = df.copy()
    d = d[(d["fit_ok"] == 1) & (d["family"] == args.family)].copy()
    if args.candidate != "all":
        d = d[d["candidate_L"] == args.candidate].copy()
    d = d[np.isfinite(d["beta"]) & np.isfinite(d["r2"])].copy()
    d = d[d["r2"] >= args.min_r2_fit].copy()
    if args.rmt_min is not None:
        d = d[d["K_gap_ratio"] >= args.rmt_min].copy()
    if args.rmt_max is not None:
        d = d[d["K_gap_ratio"] <= args.rmt_max].copy()
    return d


def add_features(df):
    d = df.copy()

    # Safe derived features.
    d["log_C_modular"] = np.log(np.maximum(d["C_modular"].astype(float), 1e-12))
    d["log_slope_ramp"] = np.log(np.maximum(np.abs(d["slope_ramp"].astype(float)), 1e-12))
    d["rmt_distance"] = np.abs(d["K_gap_ratio"].astype(float) - 0.53)
    d["rmt_score"] = np.exp(-(d["rmt_distance"] ** 2) / (2 * 0.08 ** 2))

    # Regime group for leave-one-regime-out.
    for col in ["eta_zz", "hx", "hz_random"]:
        if col not in d.columns:
            d[col] = np.nan
    d["regime"] = (
        d["eta_zz"].round(6).astype(str)
        + "_"
        + d["hx"].round(6).astype(str)
        + "_"
        + d["hz_random"].round(6).astype(str)
    )

    # Some CSVs may not have n as numeric.
    if "n" not in d.columns:
        d["n"] = np.nan

    return d


def make_feature_lists(df):
    numeric = [
        "C_modular",
        "log_C_modular",
        "K_gap_ratio",
        "rmt_distance",
        "rmt_score",
        "log_t_dip",
        "log_t_ramp",
        "slope_ramp",
        "log_slope_ramp",
        "delta3_proxy",
        "eta_zz",
        "hx",
        "hz_random",
        "j_disorder",
        "mean_MI",
        "max_MI",
        "mean_single_entropy",
        "n_edges_input",
        "n",
        "subsystem_size",
    ]
    numeric = [c for c in numeric if c in df.columns]

    categorical = [c for c in ["topology", "candidate_L"] if c in df.columns]
    return numeric, categorical


def make_preprocessor(numeric, categorical):
    try:
        enc = OneHotEncoder(handle_unknown="ignore", sparse_output=False)
    except TypeError:
        enc = OneHotEncoder(handle_unknown="ignore", sparse=False)

    pre = ColumnTransformer(
        transformers=[
            ("num", Pipeline([
                ("imputer", SimpleImputer(strategy="median")),
                ("scaler", StandardScaler()),
            ]), numeric),
            ("cat", Pipeline([
                ("imputer", SimpleImputer(strategy="most_frequent")),
                ("onehot", enc),
            ]), categorical),
        ],
        remainder="drop",
    )
    return pre


def models(random_state):
    return {
        "linear": LinearRegression(),
        "ridge_1": Ridge(alpha=1.0),
        "ridge_10": Ridge(alpha=10.0),
        "lasso_001": Lasso(alpha=0.01, max_iter=20000),
        "lasso_01": Lasso(alpha=0.1, max_iter=20000),
        "random_forest": RandomForestRegressor(
            n_estimators=400,
            max_depth=None,
            min_samples_leaf=3,
            random_state=random_state,
        ),
        "gradient_boosting": GradientBoostingRegressor(
            n_estimators=250,
            learning_rate=0.04,
            max_depth=3,
            random_state=random_state,
        ),
    }


def eval_predictions(y, ypred):
    return {
        "r2": float(r2_score(y, ypred)),
        "rmse": float(np.sqrt(mean_squared_error(y, ypred))),
        "mae": float(mean_absolute_error(y, ypred)),
    }


def cv_predict_model(model, pre, X, y, cv):
    pipe = Pipeline([("pre", pre), ("model", model)])
    pred = cross_val_predict(pipe, X, y, cv=cv)
    return pred


def leave_group_predict(model, pre, X, y, groups):
    logo = LeaveOneGroupOut()
    pipe = Pipeline([("pre", pre), ("model", model)])
    pred = np.full_like(y, fill_value=np.nan, dtype=float)
    rows = []
    for fold, (train, test) in enumerate(logo.split(X, y, groups=groups)):
        if len(np.unique(y[train])) < 2:
            continue
        pipe.fit(X.iloc[train], y[train])
        p = pipe.predict(X.iloc[test])
        pred[test] = p
        metrics = eval_predictions(y[test], p) if len(test) >= 2 else {"r2": np.nan, "rmse": np.nan, "mae": np.nan}
        rows.append({
            "fold": fold,
            "heldout_group": str(np.asarray(groups)[test][0]),
            "n_train": int(len(train)),
            "n_test": int(len(test)),
            **metrics,
        })
    return pred, pd.DataFrame(rows)


def feature_names(pre, numeric, categorical):
    names = []
    names.extend(numeric)
    try:
        cat_names = pre.named_transformers_["cat"].named_steps["onehot"].get_feature_names_out(categorical)
        names.extend(list(cat_names))
    except Exception:
        names.extend(categorical)
    return names


def save_pred_plot(y, pred, out, name, title):
    mask = np.isfinite(pred) & np.isfinite(y)
    if mask.sum() < 3:
        return
    yy = y[mask]
    pp = pred[mask]
    plt.figure(figsize=(6, 6))
    plt.scatter(yy, pp, s=35, alpha=0.75)
    mn = min(yy.min(), pp.min())
    mx = max(yy.max(), pp.max())
    plt.plot([mn, mx], [mn, mx], "--")
    plt.xlabel("beta true")
    plt.ylabel("beta predicted")
    plt.title(title)
    plt.tight_layout()
    plt.savefig(out / name, dpi=220)
    plt.close()


def main():
    args = parse_args()
    out = Path(args.output_dir)
    out.mkdir(parents=True, exist_ok=True)

    df_raw = read_csvs(args.input_csv)
    df = filter_df(df_raw, args)
    df = add_features(df)

    if len(df) < 10:
        raise SystemExit(f"Not enough rows after filtering: {len(df)}")

    numeric, categorical = make_feature_lists(df)
    pre = make_preprocessor(numeric, categorical)

    X = df[numeric + categorical].copy()
    y = df["beta"].astype(float).values

    print("=" * 90)
    print("PAPER 14 — beta regression v1")
    print("=" * 90)
    print(f"Rows after filtering : {len(df)}")
    print(f"Candidate            : {args.candidate}")
    print(f"Family               : {args.family}")
    print(f"Min spectral R2      : {args.min_r2_fit}")
    print(f"Numeric features     : {numeric}")
    print(f"Categorical features : {categorical}")
    print(f"Output               : {out}")

    rows = []
    pred_store = {}

    model_dict = models(args.random_state)

    # Standard KFold.
    kfold = KFold(n_splits=min(5, len(df)), shuffle=True, random_state=args.random_state)

    for name, model in model_dict.items():
        pred = cv_predict_model(model, pre, X, y, kfold)
        m = eval_predictions(y, pred)
        rows.append({"model": name, "cv": "kfold", "n": int(len(df)), **m})
        pred_store[(name, "kfold")] = pred

    # Leave-one-topology-out.
    if "topology" in df.columns and df["topology"].nunique() >= 2:
        groups = df["topology"].astype(str).values
        for name, model in model_dict.items():
            pred, foldtab = leave_group_predict(model, pre, X, y, groups)
            m = eval_predictions(y[np.isfinite(pred)], pred[np.isfinite(pred)])
            rows.append({"model": name, "cv": "leave_one_topology", "n": int(np.isfinite(pred).sum()), **m})
            pred_store[(name, "leave_one_topology")] = pred
            foldtab.to_csv(out / f"folds_leave_one_topology_{name}.csv", index=False)

    # Leave-one-regime-out.
    if "regime" in df.columns and df["regime"].nunique() >= 2:
        groups = df["regime"].astype(str).values
        # too many tiny groups can be noisy, but keep it.
        for name, model in model_dict.items():
            pred, foldtab = leave_group_predict(model, pre, X, y, groups)
            m = eval_predictions(y[np.isfinite(pred)], pred[np.isfinite(pred)])
            rows.append({"model": name, "cv": "leave_one_regime", "n": int(np.isfinite(pred).sum()), **m})
            pred_store[(name, "leave_one_regime")] = pred
            foldtab.to_csv(out / f"folds_leave_one_regime_{name}.csv", index=False)

    results = pd.DataFrame(rows).sort_values(["cv", "r2"], ascending=[True, False])
    results.to_csv(out / "beta_regression_results.csv", index=False)

    # Fit best KFold model for feature importance/permutation.
    best_row = results[results["cv"] == "kfold"].sort_values("r2", ascending=False).iloc[0]
    best_name = best_row["model"]
    best_model = model_dict[best_name]
    best_pipe = Pipeline([("pre", pre), ("model", best_model)])
    best_pipe.fit(X, y)

    # Feature names after preprocessing.
    fitted_pre = best_pipe.named_steps["pre"]
    names = feature_names(fitted_pre, numeric, categorical)

    # Permutation importance on training data as diagnostic only.
    try:
        perm = permutation_importance(
            best_pipe, X, y,
            n_repeats=30,
            random_state=args.random_state,
            scoring="r2",
        )
        imp = pd.DataFrame({
            "feature": numeric + categorical,
            "importance_mean": perm.importances_mean,
            "importance_std": perm.importances_std,
        }).sort_values("importance_mean", ascending=False)
        imp.to_csv(out / "permutation_importance_raw_features.csv", index=False)
    except Exception as exc:
        imp = pd.DataFrame({"error": [str(exc)]})
        imp.to_csv(out / "permutation_importance_raw_features.csv", index=False)

    # External train/test if requested.
    external_metrics = None
    if args.test_csv is not None:
        test_raw = read_csvs([args.test_csv])
        test = filter_df(test_raw, args)
        test = add_features(test)
        if len(test) > 0:
            Xte = test[numeric + categorical].copy()
            yte = test["beta"].astype(float).values
            pred_te = best_pipe.predict(Xte)
            external_metrics = eval_predictions(yte, pred_te)
            external_metrics["n_test"] = int(len(test))
            test_out = test.copy()
            test_out["beta_pred"] = pred_te
            test_out["beta_residual"] = test_out["beta"] - test_out["beta_pred"]
            test_out.to_csv(out / "external_test_predictions.csv", index=False)
            save_pred_plot(yte, pred_te, out, "fig_external_test_pred.png", "External test beta prediction")
        else:
            external_metrics = {"n_test": 0, "error": "No rows after filtering"}

    # Save predictions for best modes.
    for (name, cv), pred in pred_store.items():
        if name == best_name or cv in ["leave_one_topology", "leave_one_regime"]:
            tmp = df.copy()
            tmp["beta_pred"] = pred
            tmp["beta_residual"] = tmp["beta"] - tmp["beta_pred"]
            tmp.to_csv(out / f"predictions_{cv}_{name}.csv", index=False)

    # Plots for best model under each CV.
    for cv in results["cv"].unique():
        sub = results[results["cv"] == cv].sort_values("r2", ascending=False)
        if len(sub) == 0:
            continue
        row = sub.iloc[0]
        key = (row["model"], cv)
        if key in pred_store:
            save_pred_plot(y, pred_store[key], out, f"fig_pred_{cv}_{row['model']}.png",
                           f"Best {cv}: {row['model']}")

    summary = {
        "experiment": "BuP Paper 14 beta regression v1",
        "n_rows": int(len(df)),
        "candidate": args.candidate,
        "family": args.family,
        "min_r2_fit": args.min_r2_fit,
        "rmt_min": args.rmt_min,
        "rmt_max": args.rmt_max,
        "numeric_features": numeric,
        "categorical_features": categorical,
        "best_kfold_model": str(best_name),
        "best_kfold_metrics": best_row.to_dict(),
        "external_test_metrics": external_metrics,
    }

    with open(out / "beta_regression_summary.json", "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)

    df.to_csv(out / "beta_regression_filtered_dataset.csv", index=False)

    print()
    print("Results:")
    print(results.to_string(index=False))

    print()
    print("Best KFold model:")
    print(best_row.to_string())

    if external_metrics is not None:
        print()
        print("External test metrics:")
        print(external_metrics)

    print()
    print("Permutation importance, raw features:")
    try:
        print(imp.head(20).to_string(index=False))
    except Exception:
        pass

    print()
    print("Files written:")
    for p in sorted(out.iterdir()):
        if p.is_file():
            print("  -", p)

    print("\nDone.")


if __name__ == "__main__":
    main()
